# Generated by Django 5.1 on 2025-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='valor',
        ),
        migrations.AddField(
            model_name='historico',
            name='timestamp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='sig',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(),
        ),
    ]
