# Generated by Django 5.1 on 2025-06-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_historico_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(choices=[('contador', 'contador'), ('umidade', 'umidade'), ('temperatura', 'temperatura'), ('luminosidade', 'luminosidade')], max_length=255),
        ),
    ]
